### ISSUE TITLE
[BUG] build issue in container - requires GPU

### ISSUE THREAD

**Issue by evelynmitchell** [kyegomez/swarms-pytorch#12]
Dockerfile:
```
FROM python:3.9-slim
RUN apt-get update && apt-get -y install libgl1-mesa-dev libglib2.0-0 build-essential; apt-get clean
RUN pip install opencv-contrib-python-headless

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/swarm_cloud

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
# Install the 'swarms' package, assuming it's available on PyPI
RUN pip install swarms

# Copy the rest of the application
COPY . .
```

The error is related to mamba-ssm:
```
RUN pip install --no-cache-dir -r requirements.txt:                    
0.763 Collecting torch (from -r requirements.txt (line 1))                      
0.847   Downloading torch-2.1.2-cp39-cp39-manylinux1_x86_64.whl.metadata (25 kB)
0.877 Collecting einops (from -r requirements.txt (line 2))                     
0.884   Downloading einops-0.7.0-py3-none-any.whl.metadata (13 kB)              
1.117 Collecting pandas (from -r requirements.txt (line 3))
1.126   Downloading pandas-2.1.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
1.199 Collecting zetascale (from -r requirements.txt (line 4))
1.276   Downloading zetascale-1.2.1-py3-none-any.whl.metadata (15 kB)
1.297 Collecting mamba-ssm (from -r requirements.txt (line 5))
1.304   Downloading mamba_ssm-1.1.0.tar.gz (34 kB)
1.318   Preparing metadata (setup.py): started
1.618   Preparing metadata (setup.py): finished with status 'error'
1.634   error: subprocess-exited-with-error
1.634   
1.634   × python setup.py egg_info did not run successfully.
1.634   │ exit code: 1
1.634   ╰─> [6 lines of output]
1.634       Traceback (most recent call last):
1.634         File "<string>", line 2, in <module>
1.634         File "<pip-setuptools-caller>", line 34, in <module>
1.634         File "/tmp/pip-install-2fselg6h/mamba-ssm_3266d6b1d5bd4ecfb3810be1763d407b/setup.py", line 8, in <module>
1.634           from packaging.version import parse, Version
1.634       ModuleNotFoundError: No module named 'packaging'
1.634       [end of output]
1.634   
1.634   note: This error originates from a subprocess, and is likely not a problem with pip.
1.639 error: metadata-generation-failed
1.639 
1.639 × Encountered error while generating package metadata.
1.639 ╰─> See above for output.
1.639 
1.639 note: This is an issue with the package mentioned above, not pip.
1.639 hint: See above for details.
------
Dockerfile:20
--------------------
  18 |     COPY requirements.txt .
  19 |     RUN pip install --upgrade pip
  20 | >>> RUN pip install --no-cache-dir -r requirements.txt
  21 |     
  22 |     # Install the 'swarms' package, assuming it's available on PyPI
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
```

I believe this is related to this mamba-ssm issue:
https://github.com/state-spaces/mamba/issues/55
which requires nvcc to compile, so can't be compiled on a CPU.

T

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms-pytorch/issues/12">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms-pytorch/issues/12/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms-pytorch/issues/12/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@evelynmitchell this has been fixed please update
